### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by caseywatts** [mroswell/legislative-committee-maps#7]
Sometimes the committees list popup won't load because of this CORS error:

> XMLHttpRequest cannot load http://openstates.org/api/v1/committees/?state=al&fields=members%2Ccommittee%2Csubcommittee%2Cchamber&apikey=9e3e71730ae34e1ebbf4dd0e1c346c07. The 'Access-Control-Allow-Origin' header has a value 'http://legislativecommittees.org' that is not equal to the supplied origin. Origin 'http://localhost:8000' is therefore not allowed access.

To replicate:
1. Go to `legislativecommittees.org` in one tab and `localhost:8000` in another (or refresh each of the tabs)
2. In each, open the same state using the dropdown in the top-right
3. The second one you try will not load, and you will get the error above

**Comment by caseywatts** [comment]
I'm not sure if this is very relevant, but it's a pretty high-voted SO post. It probably has some important relevant concepts in there at least.
http://stackoverflow.com/questions/20035101/no-access-control-allow-origin-header-is-present-on-the-requested-resource

**Comment by paultag** [comment]
Open States CORS should be patched up to allow `*`, rather then trying to define the origin

Should be in better shape now
